### ISSUE TITLE
Changes for clarity

### ISSUE THREAD

**Issue by ProbablePrime** [voxelbonecloud/headless-docker#2]
The repositories layout is becoming confusing and overwhelming due to the varieties of examples.

My advice would be to keep the root of the repository as minimal as possible and to present a "known good path", you can then put the other examples that might be more complex in an examples folder.

**Comment by bredo228** [comment]
Extra examples have been moved into https://github.com/voxelbonecloud/headless-docker/tree/main/examples, this should be sorted out now
